version: "3"

networks:
  default-network:
    external: false
    
services:
        web:
            build:
                  context: .
                  dockerfile: Dockerfile
            container_name: web
            ports: 
                - "8080:5000"
            volumes:
                - ".:/app"
            links: 
                - "redis"
            networks:
                - default-network
        redis: 
            image: "redis:alpine"
            ports: 
                - "6380:6379"
            networks:
                - default-network
        mongo: 
            image: "mongo"
            ports: 
                - "27018:27017"
            networks:
                - default-network

